config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # devise_for :views

  root "pins#index"

  resources :users, only: [:show, :edit]
  resources :boards
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :name, presence: true

  has_many :pins
  has_many :user_boards
  has_many :users,  through: :user_boards

end

app/models/board_pin.rb
class BoardPin < ApplicationRecord
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  validates :image, presence: true

  belongs_to :user
  belongs_to :board

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :user_boards
  has_many :boards, through: :user_boards

end

app/models/user_bord.rb
class UserBord < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Boads.all.order("created_at DESC")
    @board = Boads.new
  end

  def new
    @board = Boads.new
  end

  def create
    @board = Boads.new(board_params)
    if @board.save
      redirect_to @board
    else
      render 'new'
    end
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, expect: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
    @pin = Pin.new
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfuly create new Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was Successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image).merge(user_id: current_user.id)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pin = Pin.find(params[:id])
    @pins = Pin.all.order("created_at DESC")
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pinterest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navber.navber-default
      .container
        .navber-header
          / = simple_form_for @pin do |f|
          .navbar-brand
            .navbar-brand_row
              = link_to root_path do
                %i.fa.fa-pinterest.fa-2x
                %p ホームフィード
            / .form-group
            /   = f.input :title

          - if user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %li.navbar-right_btn
                = link_to root_path do
                  %i.fa.fa-compass.fa-2x
                  %p ピックアップ
              %li.navbar-right_btn
                %a{href: "/users/#{current_user.id}"}
                  %i.fa.fa-user.fa-2x
                  %p マイページ
              %li.navbar-right_btn
                = link_to root_path do
                  %i.fa.fa-commenting-o.fa-2x
                  %p お知らせ
              %li.navbar-right_btn
                = link_to new_pin_path do
                  %i.fa.fa-pencil-square-o.fa-2x
                  %p 投稿

          - else
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign Up", new_user_registration_path
              %li= link_to "Sign In", new_user_session_path
      .row
        -flash.each do |name,msg|
          = content_tag :div, msg, class: "alert alert-info"

        = yield

app/views/modal/_newboard-modal.html.haml
#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title New message
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %form
          .form-group
            %label.form-control-label{:for => "recipient-name"} Recipient:
            %input#recipient-name.form-control{:type => "text"}/
          .form-group
            %label.form-control-label{:for => "message-text"} Message:
            %textarea#message-text.form-control
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Send message

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  -if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.errors.full_message.each do |msg|
          %li= msg
  .from-group
    = f.input :image, input_html: { class: 'form-control'}

  .from-group
    = f.input :title, input_html: { class: 'form-control'}

  .from-group
    = f.input :description, input_html: { class: 'form-control' }

  =f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Pin
  = image_tag @pin.image.url(:medium)
  = render 'form'
  = link_to "Cancel", pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      .panel-wrapper
        .panel-body
          %a
            = link_to (image_tag pin.image.url), pin
          .index_modal-btn
            %button.btn.btn-danger{"data-target" => "#exampleModalLong", "data-toggle" => "modal", :type => "button"}
              保存
            / Modal
            #exampleModalLong.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLongTitle", :role => "dialog", :tabindex => "-1"}
              .modal-dialog{:role => "document"}
                .modal-content
                  .modal-content_body
                    .row-left
                      .row-left_body
                        .row-left_body-image
                          = image_tag pin.image.url
                        / %p
                        /   = pin.title
                    .row-right
                      .row-right_header
                        .container-fluid
                          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                            %span{"aria-hidden" => "true"} ×
                          %h2 ボードを選択
                      .row-right_body
                        .popularity-boards
                          .popularity-boards_header
                            人気のボード
                          .popularity-boards_body
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p ファッション
                              %button.btn.btn-danger{:type => "button"} 保存
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p 映画
                              %button.btn.btn-danger{:type => "button"} 保存
                        .all-boards
                          .all-boards_header
                            すべてのボード
                          .all-boards_body
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p ファッション
                              %button.btn.btn-danger{:type => "button"} 保存
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p 映画
                              %button.btn.btn-danger{:type => "button"} 保存
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p ホームアイデア
                              %button.btn.btn-danger{:type => "button"} 保存
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p ヘアスタイル
                              %button.btn.btn-danger{:type => "button"} 保存
                            %a.bord-table
                              .bord-table_img
                                = image_tag pin.image.url
                              %p 料理
                              %button.btn.btn-danger{:type => "button"} 保存

                      .modal-content_footer
                        %a.new-board
                          %i.fa.fa-plus-circle.fa-3x
                          %p 新規ボードを作成
                        / %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
                        / %button.btn.btn-danger{:type => "button"} 保存
          .index_shere-pin
            %button.btn.btn-default{"data-target" => "#exampleModalLong", "data-toggle" => "modal", :type => "button"}
              %i.fa.fa-share-square-o
        .panel-footer
          .text-btn
            = link_to "…"

app/views/pins/new.html.haml
#pins_create
  .row
    .pins-create_background-image
      .col-md-4.col-md-offset-4
        .panel.panel-default
          .panel-heading
            %h1 YOU投稿しちゃいなよ
          .panel-body
            = render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
        %p= @pin.user.email
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            = @pin.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %i.fa.fa-heart
                  = @pin.get_upvotes.size
              -if user_signed_in?
                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                = link_to "Delete", pin_path, method: :delete, data: { confirm: "消していいですか？" } ,class: "btn btn-default"

app/views/users/edit.html.haml
#user_edit
  .container
    .row-left
      .row-left_edit-menu
        %p アカウント情報
        %p お知らせ
        %p ホームフィード
        %p SNSアカウント
        %p セキュリティ
        %p アプリ

    .row-right
      .row-right_body
        .account-information
          %p アカウント情報
          .mail
            %p メールアドレス
            %p aaa.com
          .password
            %p パスワード
            %p パスワードを変更
          .language
            %p 言語
            %p 日本語
          .country-of-residence
            %p 日本(日本)
          .gender
            %p 男
            %p 女
            %p カスタム
          .privacy
            %p 検索プライバシー
            %p 検索エンジン（例：Google）でプロフィールを非表示にします。詳細
          .Personalized
            %p パーソナライズ
            %p ユーザーがアクセスするサイトを元に、表示するおすすめや広告を改善しています。詳細
            %p Pinterest のパートナーからの利用情報を元に、ユーザーに表示するおすすめや広告を改善しています。詳細
          .search-history
            %p 検索履歴をクリア
            %p 検索したキーワードを検索履歴から削除します。
          .account
            %p アカウント
            %p アカウントを解除

        .profile
          .name
            %p プロフィール
            %p 名前
          .image
          .user-name
          .self-introduction
          .housing
          .web-site

        .home-feed
          .recommended-pin

        .sns
          .elaborate
        .security
        .app

app/views/users/show.html.haml
#user_show
  .header
    %a
      %i.fa.fa-wrench.fa-2x
    %a
      %i.fa.fa-plane.fa-2x
    %a
      %i.fa.fa-ellipsis-h.fa-2x
  .body
    .user-infomation
      .user-infomation_name
        %p
          - if user_signed_in?
            = current_user.name
      .user-infomation_follow
        .followers
          10
          %p フォロワー
        .follow-up
          10
          %p フォロー中
      .user-infomation_user-image
        = image_tag @pin.image.url(:medium)
    .user-boards
      .user-boards_header
        %p ボード
        %p ピン
        %p 試してみた
      .user-boards_body
        .panel-wrapper
          %a.panel-body
            .new-board_image
              %i.fa.fa-plus-circle.fa-3x
            .panel-footer
              %p 新規ボードを作成
          - @pins.each do |pin|
            .panel-body
              .user-boards_body-image
                = image_tag pin.image.url
                .panel-footer
                  %p aaa
                  45 pin
    .user-boards_secret
      .user-boards_secret-header
        %i.fa.fa-key.fa-2x
        %p シークレットボード
        %br/
        %p このボードはあなた（及びあなたが招待したユーザー）だけが見ることができます。 詳細
      .user-boards_secret-body
        - @pins.each do |pin|
          .panel-body
            .user-boards_body-image
              = image_tag pin.image.url
            .panel-footer
              %p aaa
              45 pin